### ISSUE TITLE
Write 'proper' spawner

### ISSUE THREAD

**Issue by VGSquidaddy** [waferthinninja/Elizardbethan#16]
This requires a bit of thought as it'll be really critical to how the game plays. 

We need to make it extensible (so that new kinds of game actor can appear over time) it needs to play nice with our as-yet-unwritten object pool, have some kind of random aspect to it but still be fair and playable-with. We talked about the Super Hexagon approach of random selection of hand-coded segments.

As well as antagonists, pickups and obstacles, our spawner should also handle adding stuff to the scenery like pondweed, reeds, other flavour stuff.

**Comment by waferthinninja** [comment]
Closing this now I've added the pattern based spawner. This issue was wider than that, but I think we should create smaller more focussed issues as they come up.
